Update to Akka 2.5.2 and akka-persistence-cassandra 0.53
The delay in updating was due to a similar issue to that reported at
https://github.com/akka/akka-http/issues/1101; LiqudityServerSpec was
failing with this exception:

[JVM-3]   java.lang.NoClassDefFoundError: akka/stream/impl/StreamLayout$Module
[JVM-3]   at com.dhpcs.liquidity.server.LiquidityServerSpec.withJsonRpcWsTestProbes(LiquidityServerSpec.scala:416)
[JVM-3]   at com.dhpcs.liquidity.server.LiquidityServerSpec.$anonfun$new(3(LiquidityServerSpec.scala:241)
[JVM-3]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[JVM-3]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[JVM-3]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[JVM-3]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[JVM-3]   at org.scalatest.FreeSpecLike$$anon(.apply(FreeSpecLike.scala:407)
[JVM-3]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[JVM-3]   ...
[JVM-3]   Cause: java.lang.ClassNotFoundException: akka.stream.impl.StreamLayout$Module
[JVM-3]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[JVM-3]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[JVM-3]   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
[JVM-3]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[JVM-3]   at com.dhpcs.liquidity.server.LiquidityServerSpec.withJsonRpcWsTestProbes(LiquidityServerSpec.scala:416)
[JVM-3]   at com.dhpcs.liquidity.server.LiquidityServerSpec.$anonfun$new(3(LiquidityServerSpec.scala:241)
[JVM-3]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[JVM-3]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[JVM-3]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[JVM-3]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[JVM-3]   ...

The discussion on the above GitHub issue eventually led me to realise
that the issue was due to the test configuration's dependency on
akka-http-testkit bringing in akka-stream-testkit 2.4.18 (whereas it
needs to be 2.5.2), and the fact that the MultiJvm config _does extend_
the Test config (unlike SBT's built-in IntegrationTest config).