Fix analytics transaction projection regression
The issue was introduced with the update to mysql-connector-java 8 but
didn't present itself until the update to MySQL 8.0 (which in production
involved a backup and restore of the journal followed by re-projection
to the analytics tables) because none of the existing test cases
involved transactions greater than 5000. The initial production
re-projection however was failing because such transactions do exist
there.

This custom Meta[BigDecimal] fixes the issue by mapping to and from
string, rather than java.math.BigDecimal, which works because the issue
was with the parsing of the result of a source account value
read as a java.math.BigDecimal:

WARN a.s.s.RestartWithBackoffSource RestartWithBackoffSource(akka://liquidity) - Restarting graph due to failure. stack_trace:
java.sql.SQLDataException: Invalid integer format for value '-455669449960000007604982'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:114)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:92)
at com.mysql.cj.jdbc.result.ResultSetImpl.getBigDecimal(ResultSetImpl.java:710)
at com.zaxxer.hikari.pool.HikariProxyResultSet.getBigDecimal(HikariProxyResultSet.java)
at doobie.util.MetaInstances.$anonfun$BigDecimalMeta$1(meta.scala:208)
at doobie.util.MetaInstances.$anonfun$BigDecimalMeta$1$adapted(meta.scala:208)
at doobie.util.Get.unsafeGetNonNullable(get.scala:27)
at doobie.util.Read$.$anonfun$fromGet$1(read.scala:75)
at doobie.util.Read$.$anonfun$fromGet$1$adapted(read.scala:75)
at doobie.util.Read.$anonfun$get$1(read.scala:57)
at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:114)
at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:85)
at cats.effect.internals.IORunLoop$.startCancelable(IORunLoop.scala:41)
at cats.effect.internals.IOBracket$BracketStart.run(IOBracket.scala:74)
at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:70)
at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:36)
at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:93)
at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:93)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:93)
at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:44)
at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:60)
at cats.effect.internals.IOBracket$BracketStart.apply(IOBracket.scala:41)
at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:134)
at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:336)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:357)
at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:303)
at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.mysql.cj.exceptions.NumberOutOfRange: Invalid integer format for value '-455669449960000007604982'
at com.mysql.cj.util.StringUtils.getLong(StringUtils.java:412)
at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeInt8(MysqlTextValueDecoder.java:220)
at com.mysql.cj.result.StringConverter.createFromBytes(StringConverter.java:118)
at com.mysql.cj.protocol.a.MysqlBinaryValueDecoder.decodeByteArray(MysqlBinaryValueDecoder.java:226)
at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:143)
at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:250)
at com.mysql.cj.protocol.a.result.BinaryBufferRow.getValue(BinaryBufferRow.java:244)
at com.mysql.cj.jdbc.result.ResultSetImpl.getNonStringValueFromRow(ResultSetImpl.java:656)
... 31 more