Fix unit test race condition introduced in 8e350a41
The test sink was failing to materialize with this error:
akka.actor.InvalidActorNameException: actor name [testProbe-1] is not
unique!